# Generated by Django 2.2.12 on 2022-04-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_backend_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
